name: PR

on:
  pull_request:

permissions:
  contents: read

jobs:
  tests:
    uses: ./.github/workflows/_run-tests.yml

  dependency-review:
    name: Dependency Review scan
    uses: govuk-pay/pay-ci/.github/workflows/_run-dependency-review.yml@591ff32de6cd3c9a0f4af2506f8938e7bd5decaa
