name: PR

on:
  pull_request:

permissions:
  contents: read

jobs:
  tests:
    uses: ./.github/workflows/_run-tests.yml

# temporarily disable
#  dependency-review:
#    name: Dependency Review scan
#    uses: govuk-pay/pay-ci/.github/workflows/_run-dependency-review.yml@8597f9957716cb928c22ed66ee0704a24798ce6e
