name: Visual regression

on:
  pull_request:
    branches:
      - 'master'
    paths:
      - 'source/**'
  push:
    branches:
      - 'master'
    paths:
      - 'source/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  visual-regression:
    name: Start visual regression build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - name: Setup Ruby
        uses: ruby/setup-ruby@9669f3ee51dc3f4eda8447ab696b3ab19a90d14b
        with:
          ruby-version: '.ruby-version'
          bundler-cache: true
      - name: Setup Node
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Install and Build
        run: |
          npm ci
          bundle exec middleman build
      - name: Run Percy tasks
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
        run: npm run percy
