name: Visual regression

on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'source/**'
  push:
    branches:
      - 'main'
    paths:
      - 'source/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  visual-regression:
    name: Start visual regression build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
      - name: Setup Ruby
        uses: ruby/setup-ruby@7bae1d00b5db9166f4f0fc47985a3a5702cb58f0
        with:
          ruby-version: '.ruby-version'
          bundler-cache: true
      - name: Setup Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Install and Build
        run: |
          npm ci
          bundle exec middleman build
      - name: Run Percy tasks
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
        run: npm run percy
